# Generated by Django 5.2.12 on 2026-03-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_add_lookup_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='priority',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
